import Head from 'next/head'
import Link from "next/link"
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from "axios"

export default function Home() {
  const [infos,setInfos]=useState([]);
  useEffect(()=>{
    axios.get("https://jsonplaceholder.typicode.com/albums").then((res)=>{
      console.log(res.data)
      axios.get("https://jsonplaceholder.typicode.com/photos").then((res2)=>{
        console.log("res2:",res2.data)
        const temp = res.data.slice(0,50).map((e,ii)=>{return {title:e,image:res2.data[res2.data.reverse().findIndex(ee=>ee.albumId==e.id)]}})
        setInfos(temp)
        console.log("temp",temp)
      }).catch((err)=>console.log(err))
    }).catch((err)=>console.log(err))
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          {infos?.slice(0,15).map((e,i)=>
            <Link key={i} href={`/details/${e.title.userId}`}>
              <div className={styles.card}>
              
              <h2>
              {e.title.title}
            </h2>
            <img src={e.image.url} alt="jhdf"/>
            
            </div></Link>)}
          
        </div>
      </main>
    </div>
  )
}
