import React from 'react'
import Head from 'next/head'
import NavBar from '../Copmonets/NavBar';
import Footer from '../Copmonets/Footer';

export const layout = ({children}) => {
    return (
        <div>

<Head>
        <title>Header and Footer</title>
        <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
        crossorigin="anonymous">
        </link>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
            <NavBar></NavBar>
            
            {children}
            <Footer></Footer>
          
        </div>
    )
}

export default layout;